name: pocketbase_dart_generator
description: Generate Dart classes from pocketbase endpoint.
version: 1.0.0
environment:
  sdk: ">=2.19.0-168.0.dev <3.0.0"
dependencies:
  args: ^2.3.1
  dart_style: ^2.2.4
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  json_annotation: ^4.7.0
  pocketbase: ^0.4.1
  recase: ^4.0.0
  mustache_template: ^2.0.0
dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.2.0
  hive_generator: ^1.1.3
  json_serializable: ^6.4.0
  lints: ^2.0.0
  test: ^1.16.0
