name: pocketbase_dart_generator
description: Generate Dart classes from pocketbase endpoint.
version: 1.0.0
environment:
  sdk: ">=2.19.0-168.0.dev <3.0.0"
dependencies:
  args: ^2.3.1
  dart_style: ^2.2.4
  hive: ^2.2.3
  mustache_recase: ^2.2.0
  mustache_template: ^2.0.0
  pocketbase: ^0.17.0-rc
  recase: ^4.0.0
dev_dependencies:
  lints: ^2.0.0
  sqlite3: ^2.1.0
  test: ^1.16.0
